{{- if .Values.externalAccess.enabled }}
{{- if not (lookup "rbac.authorization.k8s.io/v1" "Role" .Release.Namespace .Values.serviceAccount.name) }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pravega.commonLabels" . | indent 4 }}
rules:
- apiGroups:
  - pravega.pravega.io
  resources:
  - "*"
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
{{- end }}
{{- end }}
