{{- if .Values.externalAccess.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pravega.fullname" . }}-service-account 
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pravega.commonLabels" . | indent 4 }}
{{- end }}
