{{- if .Values.externalAccess.enabled }}
{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace .Values.serviceAccount.name) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "pravega.commonLabels" . | indent 4 }}
{{- end }}
{{- end }}
